export const DataSourceLabel = ({ source, license, date }: { source: string; license?: string; date?: string }) => (
  <div className="inline-flex items-center space-x-1 px-2 py-1 rounded bg-blue-900/30 border border-blue-700/50 text-blue-400 text-xs font-medium">
    <span>{source}</span>
    {license && <span className="opacity-75">| {license}</span>}
    {date && <span className="opacity-75">| {date}</span>}
  </div>
);

export const ModelOutputLabel = ({ solver }: { solver: string }) => (
  <div className="inline-flex px-2 py-1 rounded bg-cyan-900/30 border border-cyan-700/50 text-cyan-400 text-xs font-medium tracking-wide">
    MODEL OUTPUT &mdash; Generated by {solver}
  </div>
);

export const CalculatedLabel = () => (
  <div className="inline-flex px-2 py-1 rounded bg-green-900/30 border border-green-700/50 text-green-400 text-xs font-medium">
    CALCULATED &mdash; 2D-VPMM Real Engine
  </div>
);

export const EstimatedLabel = ({ method }: { method: string }) => (
  <div className="inline-flex px-2 py-1 rounded bg-orange-900/30 border border-orange-700/50 text-orange-400 text-xs font-medium">
    ESTIMATED &mdash; {method}
  </div>
);

export const AssumedLabel = ({ rationale }: { rationale: string }) => (
  <div className="inline-flex px-2 py-1 rounded bg-yellow-900/30 border border-yellow-700/50 text-yellow-400 text-xs font-medium">
    ASSUMED &mdash; {rationale}
  </div>
);

export const DemoDataLabel = () => (
  <div className="inline-flex px-2 py-1 rounded bg-red-900/30 border border-red-700/50 text-red-400 text-xs font-medium uppercase animate-pulse">
    DEMO DATA &mdash; Sample scenario, not a validated forecast
  </div>
);

export const UnavailableLabel = () => (
  <div className="inline-flex px-2 py-1 rounded bg-gray-800 border border-gray-700 text-gray-500 text-xs font-medium">
    Not available for this dataset
  </div>
);
