"""
Breach computation API endpoint.
Connects to the real parametric breach models and reservoir routing engine.
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List, Optional
from pydantic import BaseModel
import numpy as np

from app.database import get_db

router = APIRouter()


class DamParams(BaseModel):
    height_m: float = 22.56
    crest_length_m: float = 3810.0
    crest_elevation_m: float = 102.11
    reservoir_volume_m3: float = 101000000.0
    reservoir_area_m2: float = 17400000.0
    water_level_m: float = 102.11
    dam_type: str = "earthfill"
    stage_storage: Optional[List[List[float]]] = None


class BreachComputeRequest(BaseModel):
    dam: Optional[DamParams] = None
    breach_mode: str = "overtopping"
    breach_method: str = "froehlich"
    user_params: Optional[dict] = None
    simulation_duration_s: Optional[float] = None
    dt_output: float = 60.0


class BreachComputeResponse(BaseModel):
    time_s: List[float]
    discharge_m3s: List[float]
    water_level_m: List[float]
    breach_width_m: List[float]
    peak_discharge_m3s: float
    time_to_peak_s: float
    total_volume_m3: float
    mass_error_pct: float
    method: str
    breach_params: dict
    label: str = "MODEL OUTPUT"


def _do_compute_breach(req: BreachComputeRequest):
    from app.breach.parametric import (
        DamParameters, BreachMode, BreachMethod, compute_breach_params
    )
    from app.breach.reservoir import (
        compute_breach_hydrograph, ReservoirConfig
    )
    
    dam_input = req.dam or DamParams()

    dam = DamParameters(
        height_m=dam_input.height_m,
        crest_length_m=dam_input.crest_length_m,
        crest_elevation_m=dam_input.crest_elevation_m,
        reservoir_volume_m3=dam_input.reservoir_volume_m3,
        reservoir_area_m2=dam_input.reservoir_area_m2,
        water_level_m=dam_input.water_level_m,
        dam_type=dam_input.dam_type,
        stage_storage=[tuple(s) for s in dam_input.stage_storage] if dam_input.stage_storage else None,
    )
    
    try:
        mode = BreachMode(req.breach_mode.lower())
    except ValueError:
        mode = BreachMode.OVERTOPPING
    
    try:
        method = BreachMethod(req.breach_method.lower())
    except ValueError:
        method = BreachMethod.FROEHLICH
    
    breach_params = compute_breach_params(dam, mode, method, req.user_params)
    routing_config = ReservoirConfig(
        dt_output=req.dt_output,
        simulation_duration_s=req.simulation_duration_s or 21600.0,
    )
    
    hydrograph = compute_breach_hydrograph(dam, breach_params, mode, config=routing_config)
    
    return BreachComputeResponse(
        time_s=hydrograph.time_s.tolist(),
        discharge_m3s=hydrograph.discharge_m3s.tolist(),
        water_level_m=hydrograph.water_level_m.tolist(),
        breach_width_m=hydrograph.breach_width_m.tolist(),
        peak_discharge_m3s=hydrograph.peak_discharge_m3s,
        time_to_peak_s=hydrograph.time_to_peak_s,
        total_volume_m3=hydrograph.total_volume_m3,
        mass_error_pct=hydrograph.mass_error_pct,
        method=hydrograph.method,
        breach_params={
            "average_width_m": breach_params.average_width_m,
            "bottom_width_m": breach_params.bottom_width_m,
            "depth_m": breach_params.depth_m,
            "formation_time_s": breach_params.formation_time_s,
            "side_slope": breach_params.side_slope,
            "peak_outflow_m3s": breach_params.peak_outflow_m3s,
            "notes": breach_params.notes,
        },
        label=f"MODEL OUTPUT — Generated by {breach_params.method}",
    )


@router.post("/{project_id}/breach/compute", response_model=BreachComputeResponse)
async def compute_breach_with_id(project_id: str, req: BreachComputeRequest):
    return _do_compute_breach(req)


@router.post("/breach/compute", response_model=BreachComputeResponse)
async def compute_breach_direct(req: BreachComputeRequest):
    return _do_compute_breach(req)
